"""
Django settings for data_lineage project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/
gro
For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Load environment variables from .env file (optional - Railway uses env vars directly)
try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass  # dotenv optional - Railway uses environment variables directly

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-a4yx6ji566+o8j07d7w8zq=4)%*%mo6i^nl0vpf=^95rb1xmxp"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '172.20.10.2', '*']  # Add your Linux server IP


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "main",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # Add for static files
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "data_lineage.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "data_lineage.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'data_lineage_eda',  # Replace with your desired database name
        'USER': 'postgres',       # Replace with your PostgreSQL username
        'PASSWORD': '123456',   # Replace with your PostgreSQL password
        'HOST': 'localhost',           # Or the IP address of your PostgreSQL server
        'PORT': '5432',                # Default PostgreSQL port
    },
    'bot_eda': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'bot_eda',  # Replace with your desired database name
        'USER': 'postgres',       # Replace with your PostgreSQL username
        'PASSWORD': '123456',   # Replace with your PostgreSQL password
        'HOST': 'localhost',           # Or the IP address of your PostgreSQL server.
        'PORT': '5432',                # Default PostgreSQL port
    }
}

DATABASE_ROUTERS = ['data_lineage.db_router.BotEdaRouter']



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"


TIME_ZONE = 'Asia/Jakarta'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [
    BASE_DIR / "main" / "static",
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# File Upload Settings
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB

# Static files for production
STATIC_ROOT = BASE_DIR / 'staticfiles'

# CSRF Settings for production
CSRF_TRUSTED_ORIGINS = [
    'https://datalineageai-production.up.railway.app',
    'http://172.20.10.2:8000',
    'http://localhost:8000',
    'http://127.0.0.1:8000',
]

# Security settings for production
SECURE_CROSS_ORIGIN_OPENER_POLICY = None
SECURE_REFERRER_POLICY = None

# Groq API Configuration
GROQ_API_KEY = ""

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'django_errors.log',
        },
        'console': {
            'level': 'ERROR',
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console'],
            'level': 'ERROR',
            'propagate': True,
        },
    },
}

# ============================================================
# PRODUCTION SETTINGS - RAILWAY + NEON
# ============================================================

import os

# Ambil semua config dari environment variables
# sehingga tidak ada credential yang hardcode di kode

# Secret key dari env var (wajib di production)
if os.environ.get('DJANGO_SECRET_KEY'):
    SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')

# Debug mode - matikan di production
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

# Allowed hosts untuk Railway
# Railway otomatis set RAILWAY_PUBLIC_DOMAIN
RAILWAY_PUBLIC_DOMAIN = os.environ.get('RAILWAY_PUBLIC_DOMAIN', '')
if RAILWAY_PUBLIC_DOMAIN:
    ALLOWED_HOSTS = [
        RAILWAY_PUBLIC_DOMAIN,
        '.railway.app',
        'localhost',
        '127.0.0.1',
    ]
else:
    # Fallback jika env var belum di-set - include Railway static domain
    ALLOWED_HOSTS = [
        'datalineageai-production.up.railway.app',
        '*.railway.app',
        'localhost',
        '127.0.0.1',
        '*',
    ]

# Database default - Neon
if os.environ.get('DATABASE_URL'):
    import dj_database_url
    db_config = dj_database_url.parse(
        os.environ.get('DATABASE_URL'),
        conn_max_age=600
    )
    db_config['OPTIONS'] = {'sslmode': 'require'}
    DATABASES['default'] = db_config

# Database bot_eda - Neon
if os.environ.get('BOT_EDA_DATABASE_URL'):
    import dj_database_url
    bot_db_config = dj_database_url.parse(
        os.environ.get('BOT_EDA_DATABASE_URL'),
        conn_max_age=600
    )
    bot_db_config['OPTIONS'] = {'sslmode': 'require'}
    DATABASES['bot_eda'] = bot_db_config

# Groq API Key
if os.environ.get('GROQ_API_KEY'):
    GROQ_API_KEY = os.environ.get('GROQ_API_KEY')

# Whitenoise untuk static files
MIDDLEWARE_LIST = list(MIDDLEWARE)
if 'whitenoise.middleware.WhiteNoiseMiddleware' not in MIDDLEWARE_LIST:
    MIDDLEWARE_LIST.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')
    MIDDLEWARE = MIDDLEWARE_LIST

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
