# Generated by Django 5.2.3 on 2026-02-02 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_rename_pic_job_jobdetail_developer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobdetail",
            name="developer",
        ),
        migrations.AddField(
            model_name="jobdetail",
            name="developer_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="developed_jobs",
                to="main.jobdeveloper",
            ),
        ),
        migrations.AddField(
            model_name="jobdetail",
            name="pic_job",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
