# Generated by Django 5.2.3 on 2026-02-02 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_remove_jobdetail_developer_jobdetail_developer_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="jobdetail",
            old_name="developer_id",
            new_name="developer",
        ),
    ]
