# Generated by Django 5.2.3 on 2026-02-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_rename_developer_id_jobdetail_developer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobdetail",
            name="developer",
        ),
        migrations.AddField(
            model_name="jobdetail",
            name="developers",
            field=models.ManyToManyField(
                blank=True, related_name="developed_jobs", to="main.jobdeveloper"
            ),
        ),
        migrations.AlterField(
            model_name="jobdeveloper",
            name="department",
            field=models.CharField(
                choices=[
                    ("DATA MANAGEMENT", "DATA MANAGEMENT"),
                    ("RETAIL BANKING ANALYTICS", "RETAIL BANKING ANALYTICS"),
                    ("WHOLESALE BANKING ANALYTICS", "WHOLESALE BANKING ANALYTICS"),
                    ("DATA GOVERNANCE", "DATA GOVERNANCE"),
                    ("CAMPAIGN MANAGEMENT", "CAMPAIGN MANAGEMENT"),
                    ("OTHER", "OTHER"),
                ],
                default="OTHER",
                max_length=255,
            ),
        ),
    ]
