# Generated by Django 5.2.3 on 2025-07-02 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Table",
            fields=[
                ("table_id", models.AutoField(primary_key=True, serialize=False)),
                ("table_name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("table_columns", models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ParentChildRelationship",
            fields=[
                (
                    "relationship_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "child_table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_relationships",
                        to="main.table",
                    ),
                ),
                (
                    "parent_table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_relationships",
                        to="main.table",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ColumnUsedInRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("column_used_in_relationship", models.JSONField()),
                (
                    "parent_table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_columns",
                        to="main.table",
                    ),
                ),
            ],
        ),
    ]
