# Generated by Django 5.2.3 on 2025-07-03 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parentchildrelationship",
            name="child_table",
        ),
        migrations.RemoveField(
            model_name="parentchildrelationship",
            name="parent_table",
        ),
        migrations.RemoveField(
            model_name="table",
            name="description",
        ),
        migrations.RemoveField(
            model_name="table",
            name="table_columns",
        ),
        migrations.DeleteModel(
            name="ColumnUsedInRelationship",
        ),
        migrations.DeleteModel(
            name="ParentChildRelationship",
        ),
    ]
