# Generated by Django 5.2.3 on 2025-07-04 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_remove_parentchildrelationship_child_table_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Relationship",
            fields=[
                (
                    "relationship_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("job_name", models.CharField(max_length=255)),
                (
                    "table1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="table1",
                        to="main.table",
                    ),
                ),
                (
                    "table2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="table2",
                        to="main.table",
                    ),
                ),
            ],
            options={
                "unique_together": {("table1", "table2")},
            },
        ),
    ]
