# Generated by Django 5.2.3 on 2025-12-23 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_relationship"),
    ]

    operations = [
        migrations.CreateModel(
            name="TableDetail",
            fields=[
                ("details_id", models.AutoField(primary_key=True, serialize=False)),
                ("column_name", models.CharField(max_length=255)),
                (
                    "column_desc",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("data_type", models.CharField(max_length=50)),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="columns",
                        to="main.table",
                    ),
                ),
            ],
            options={
                "verbose_name": "Table Detail",
                "verbose_name_plural": "Table Details",
                "unique_together": {("table", "column_name")},
            },
        ),
    ]
