# Generated by Django 5.2.3 on 2025-12-23 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_tabledetail"),
    ]

    operations = [
        migrations.AddField(
            model_name="table",
            name="table_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DATAMART", "DATAMART"),
                    ("SOURCE DATA", "SOURCE DATA"),
                    ("STAGGING", "STAGGING"),
                    ("OTHER", "OTHER"),
                ],
                default="OTHER",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="table",
            name="table_desc",
            field=models.TextField(blank=True, null=True),
        ),
    ]
