# Generated by Django 5.2.3 on 2025-12-23 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_table_table_category_table_table_desc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tabledetail",
            name="data_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
