# Generated by Django 6.0 on 2025-12-24 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_alter_tabledetail_data_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobDetail",
            fields=[
                ("job_id", models.AutoField(primary_key=True, serialize=False)),
                ("job_name", models.CharField(max_length=255, unique=True)),
                ("pic_job", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="relationship",
            unique_together={("table1", "table2", "job_name")},
        ),
        migrations.AddField(
            model_name="relationship",
            name="job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="relationships",
                to="main.jobdetail",
            ),
        ),
    ]
