# Generated by Django 5.2.3 on 2026-01-05 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_jobdetail_alter_relationship_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchemaCategoryMapping",
            fields=[
                ("mapping_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "schema_name",
                    models.CharField(
                        help_text="Contoh: STG, DWH, ODS", max_length=100, unique=True
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("DATAMART", "DATAMART"),
                            ("SOURCE DATA", "SOURCE DATA"),
                            ("STAGGING", "STAGGING"),
                            ("OTHER", "OTHER"),
                        ],
                        default="OTHER",
                        max_length=100,
                    ),
                ),
            ],
            options={
                "verbose_name": "Schema Mapping",
                "verbose_name_plural": "Schema Mappings",
            },
        ),
    ]
