# Generated by Django 5.2.3 on 2026-02-02 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_schemacategorymapping"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobUploadLogs",
            fields=[
                ("log_id", models.AutoField(primary_key=True, serialize=False)),
                ("status", models.CharField(blank=True, max_length=50, null=True)),
                ("log_message", models.TextField(blank=True, null=True)),
                ("update_time", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "job_upload_logs",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="JobUploadSessions",
            fields=[
                ("job_id", models.AutoField(primary_key=True, serialize=False)),
                ("job_name", models.CharField(blank=True, max_length=255, null=True)),
                ("job_path", models.TextField(blank=True, null=True)),
                ("pic_job", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "output_table",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("upload_time", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "job_upload_sessions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="StagingDetectedTables",
            fields=[
                ("table_id", models.AutoField(primary_key=True, serialize=False)),
                ("table_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "table_category",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "db_table": "staging_detected_tables",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="JobDeveloper",
            fields=[
                ("developer_id", models.AutoField(primary_key=True, serialize=False)),
                ("developer_name", models.CharField(max_length=255)),
                ("department", models.CharField(blank=True, max_length=255, null=True)),
                ("team", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "Job Developer",
                "verbose_name_plural": "Job Developers",
            },
        ),
        migrations.AlterField(
            model_name="schemacategorymapping",
            name="category",
            field=models.CharField(
                choices=[
                    ("DATAMART", "DATAMART"),
                    ("SOURCE DATA", "SOURCE DATA"),
                    ("STAGING", "STAGING"),
                    ("OTHER", "OTHER"),
                ],
                default="OTHER",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="schemacategorymapping",
            name="schema_name",
            field=models.CharField(
                help_text="Contoh: newdatamart.pst, prod_bm_bda_pst",
                max_length=100,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="table",
            name="table_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DATAMART", "DATAMART"),
                    ("SOURCE DATA", "SOURCE DATA"),
                    ("STAGING", "STAGING"),
                    ("OTHER", "OTHER"),
                ],
                default="OTHER",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="jobdetail",
            name="pic_job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="jobs",
                to="main.jobdeveloper",
            ),
        ),
    ]
