# Generated by Django 5.2.3 on 2026-02-02 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_jobuploadlogs_jobuploadsessions_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="jobdetail",
            old_name="pic_job",
            new_name="developer",
        ),
    ]
