# Generated by Django 6.0.7 on 2026-08-27 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_jobdetail_developer_jobdetail_developers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='job_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
